version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - ./all.env
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
      - ./data/backups:/backups
    ports:
    - "5432:5432"


  web:
    build: .
    command: gunicorn storage.wsgi --workers 1 --threads 2 --bind 0.0.0.0:8000
    restart: always
    env_file:
      - ./all.env
    volumes:
      - .:/code
      - static:/code/static/
    depends_on:
      - db
    ports:
      - "8000:8000"


  ngx:
    image: "nginx:latest"
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/code/static/
    depends_on:
      - web
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  static:
