# Generated by Django 3.2 on 2021-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
